packaging_format = 2

id = "gull"
name = "Gull"
description.en = "Simple, modern URL shortener"
description.fr = "Raccourcisseur d'URL simple et moderne"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MPL-2.0"
website = "https://s.aeoly.us/"
demo = "https://s.aeoly.us/"
code = "https://github.com/aeolyus/gull"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "400M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gull"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

[resources.sources]
    [resources.sources.main]
    url = "https://github.com/aeolyus/gull/archive/7ffce480463d31fe0555f2c9d87737bfe1d11dcf.tar.gz"
    sha256 = "1f8c23df6bfd401152bef0b2a27eee5d1982633c74bb75b2be1187689652114c"
    autoupdate.strategy = "latest_github_tag"
 
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8081
