#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

#ynh_go_install

#pushd $install_dir/
	#make run
	#ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -o $install_dir/gull
#popd

ynh_go_install
chmod u+x /etc/profile.d/goenv.sh
/etc/profile.d/goenv.sh

GOCACHE=/opt/goenv/cache
export GOCACHE
pushd $install_dir
make run
popd

ynh_go_remove

chown -R "$app:$app" "$install_dir"

#ynh_go_remove
#ynh_safe_rm "$install_dir/build/"
#ynh_safe_rm "$install_dir/build_ldap/"
#ynh_safe_rm "$install_dir/.cache/"
#ynh_safe_rm "$install_dir/go/"
#ynh_safe_rm "$install_dir/.go-version"

#chmod +x "$install_dir/gull"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="URL shortener"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
